### ISSUE TITLE
remove "quit" from popover

### ISSUE THREAD

**Issue by torikulhabib** [PlugaruT/wingpanel-indicator-sys-monitor#19]
i think remove "quit" from popover feel good

**Comment by PlugaruT** [comment]
The "Quit" from there is for some reason. I plan to develop the indicator so that it could be possible to start the indicator from the drawer. I know that now it doesn't make sense, but it will be improved this functionality

**Comment by PlugaruT** [comment]
Yes, but wingpanel indicators are not accepted in the Appstore. By design, each app published in the AppStore should have a desktop icon. Compiling the indicator is nice for power users, but not for simple users :)
