### ISSUE TITLE
Show bits per second instead of bytes per second

### ISSUE THREAD

**Issue by vjr** [PlugaruT/wingpanel-indicator-sys-monitor#22]
Hi,

Would it be possible to optionally show speed in bits instead of bytes? Meaning, show speed like "bps", "Kbps" and "Mbps" so that it matches up with what ISPs advertise as their speeds?

Thanks!

**Comment by ninhurt** [comment]
I've been searching for a way to do this... Agree it would be a good option to have.

**Comment by PlugaruT** [comment]
Guys, I am very open to new contributions. The thing is that I don't have enough time to dedicate to this project and I don't know when I will have...I do tend to do something here and there in my free time... but can't promise anything regarding this feature

**Comment by PlugaruT** [comment]
Fixed by @YESALAM in #34
