### ISSUE TITLE
Wingpanel always translucent when the indicator is present

### ISSUE THREAD

**Issue by zszoom** [PlugaruT/wingpanel-indicator-sys-monitor#28]
Nice job! But it change wingpanel into half-transparent, i want it to be transparent, or please add a tweak way.Thanks!

**Comment by PlugaruT** [comment]
Can you please elaborate more on this?
Thanks.

**Comment by PlugaruT** [comment]
I've done some investigation on this issue and it's true. Because of the indicator, the wingpanel stay always translucent. Trying to find a fix for this.
