### ISSUE TITLE
14.04 

### ISSUE THREAD

**Issue by secretrow** [PlugaruT/wingpanel-indicator-sys-monitor#36]
Hi, is this able to run on 14.04?  I tried to install the dependencies, and got 

E: Unable to locate package libwingpanel-2.0-dev
E: Couldn't find any package by regex 'libwingpanel-2.0-dev'
E: Unable to locate package meson

Thanks!

**Comment by PlugaruT** [comment]
This was tested only on elementary OS Juno. Not sure if will work on Loki.
